targets:
  $default:
    builders:
      mobx_codegen:
        options:
          generate_to_string: true
      freezed|freezed:
        generate_for:
          - lib/**/**
      json_serializable|json_serializable:
        generate_for:
          include:
            - lib/**/**
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          # any_map: false
          # checked: false
          # constructor: ""
          # create_factory: true
          # create_field_map: false
          # create_json_keys: false
          # create_per_field_to_json: false
          # create_to_json: true
          # disallow_unrecognized_keys: false
          # explicit_to_json: false
          field_rename: snake
          # generic_argument_factories: false
          # ignore_unannotated: false
          # include_if_null: true

